### ISSUE TITLE
Script error

### ISSUE THREAD

**Issue by SM2010Ficial** [Twanvanb1/Sonic-Nexus-RSDKv4#1]
Hi, the problem I have is that when trying to start the port I get an error screen that says the following:

SCRIPT PARSING FAILED

OPERANT NOT FOUND
Debugmode_Objcount

LINE NUMBER:
254

ERROR IN
Global/Ring.txt

![RSDKv4_64_rev02_GSBsT92Jlh](https://github.com/Twanvanb1/Sonic-Nexus-RSDKv4/assets/158231794/117cc208-bd14-45aa-b9d3-0635a99d8dbf)

I tried updating my scripts but it doesn't work

If you read this taking advantage: have a nice day

**Comment by Twanvanb1** [comment]
Do you have scripts turned on?
On what game are you trying to run this?
And what is the update of RSDKv4 that you are running?

**Comment by SM2010Ficial** [comment]
1. Yes
2. Sonic 2
3. 1.3.2

**Comment by Twanvanb1** [comment]
okay, because this will not work with Absolute.
Where did you get the Sonic 2 Data.rsdk from?

**Comment by SM2010Ficial** [comment]
extracting it from the mobile port

**Comment by SM2010Ficial** [comment]
...?

**Comment by Twanvanb1** [comment]
Do you even have `TxtScripts` set to `True` in your setting.ini?

**Comment by SM2010Ficial** [comment]
yup

**Comment by Twanvanb1** [comment]
Old issue, no one else has had this issue.
