### ISSUE TITLE
OPERAND NOT FOUND "DebugMode_ObjCount" Line Number 254 Error In Global/Ring.txt

### ISSUE THREAD

**Issue by MonigoteBricks** [Twanvanb1/Sonic-Nexus-RSDKv4#5]
![Captura de pantalla 2024-11-02 031026](https://github.com/user-attachments/assets/c2683660-6ba6-4484-8a70-439d4a8dde17)
OPERAND NOT FOUND "DebugMode_ObjCount" Line Number 254 Error In Global/Ring.txt
![Captura de pantalla 2024-11-02 031105](https://github.com/user-attachments/assets/98c97a36-f7e0-4a06-b7cf-9cd198ab7e6e)

**Comment by Twanvanb1** [comment]
Make sure you are on the latest version of RSDKv4 with the latest scripts for sonic 2.
Please fill in the Bug report form so i can get a better idea of the issue.

**Comment by MonigoteBricks** [comment]
I tried downloading the s2 scripts again and the problem is solved, thank you very much, I hope you have a nice day :3

**Comment by Twanvanb1** [comment]
Great, then i will close the Issue.
